### ISSUE TITLE
Low FPS when presenting and hiding side menu

### ISSUE THREAD

**Issue by navern** [Friend-LGA/LGSideMenuController#101]
I noticed that on iPhone 6+ presenting and hiding side menu FPS sometimes has a very low FPS, about 15-20. I use left menu with style LGSideMenuPresentationStyleSlideBelow and initial X offset 0. All other properties are default. My root controller is a list of messages (mostly) with not so complicated layout (screenshot - https://ibb.co/j3Z3GQ).

My temporary solution is to apply rasterization on controllers at initializing - FPS grows up to 40-45, but anyway it is far from smoothness (55-60).

Maybe I'm doing wrong?

```
[menuAndRootController.rootViewContainer.layer setShouldRasterize:true];
[menuAndRootController.leftViewContainer.layer setShouldRasterize:true];
[menuAndRootController.rootViewContainer.layer setRasterizationScale:[UIScreen mainScreen].scale];
[menuAndRootController.leftViewContainer.layer setRasterizationScale:[UIScreen mainScreen].scale];
```

**Comment by Friend-LGA** [comment]
I tried to make this library with nice performance optimisation. Shadows are drawing without layers and `QuartzCore.framework`. I use `CoreGraphics.framework` to make it faster. This class is responsible for drawing: [LGSideMenuBorderView](https://github.com/Friend-LGA/LGSideMenuController/blob/2.1.0/LGSideMenuController/LGSideMenuBorderView.m). Because of this, rasterization shouldn't have strong effect on the library itself, I think it has more effect on your views inside containers. Try to change code like this:
```objective-c
[menuAndRootController.rootView.layer setShouldRasterize:true];
[menuAndRootController.leftView.layer setShouldRasterize:true];
[menuAndRootController.rootView.layer setRasterizationScale:[UIScreen mainScreen].scale];
[menuAndRootController.leftView.layer setRasterizationScale:[UIScreen mainScreen].scale];
```
Do you have any performance changes?

**Comment by navern** [comment]
Its pretty smooth now, thanks. I also changed presentation style to "above" and now animating left menu, not complicated root controller. Anyway rasterization works good for complicated layouts, I would suggest it to anyone experiencing the similar problem.
