### ISSUE TITLE
LeftView is disappear problem

### ISSUE THREAD

**Issue by xjimi** [Friend-LGA/LGSideMenuController#11]
When i use "Personal Hotspot" and call "showLeftViewAnimated:completionHandler:"
the LeftView is disappeared
<img src="https://cloud.githubusercontent.com/assets/1509873/9654018/445ab9b4-525a-11e5-939e-438bc9468d52.PNG" width="250"/> <img src="https://cloud.githubusercontent.com/assets/1509873/9654027/516f0330-525a-11e5-837d-ce6318ff3aa0.PNG" width="250"/>

**Comment by morgman** [comment]
Did you ever resolve this?

**Comment by Tchikoo** [comment]
Same issue here, it happens when In-Call status bar is visible. You can simulate with Hardware > Toggle In-Call Status Bar.

**Comment by brightsider** [comment]
@Friend-LGA seems that bug doesn't fixed. On last commit this bug reproduced.

**Comment by Friend-LGA** [comment]
@brightsider No, checked just now, works fine

**Comment by brightsider** [comment]
@Friend-LGA I'm write to your mail. Can you see that?

**Comment by Friend-LGA** [comment]
Do you sure you use the latest version? Your problem looks the same as before.

**Comment by brightsider** [comment]
@Friend-LGA I'm use pod - pod 'LGSideMenuController', :git => 'https://github.com/Friend-LGA/LGSideMenuController.git', :commit => 'd9b5847'
In demo don't reproduce, but I'm create slide controller like in Demo. It's reproduce with any style only for Left menu.

**Comment by Friend-LGA** [comment]
Can you make simple project and send it to my email to I was able to reproduce the bug?

**Comment by brightsider** [comment]
@Friend-LGA I figured out. I use own status bar hide/show because leftViewStatusBarVisibleOptions not work on iOS 9 with View controller-based status bar appearance = NO.
And if I'm enabled statusBarAppearanceUpdate for iOS 9 - this bug reproduced sometimes.
My solution is kLGSideMenuControllerDidDismissLeftViewNotification instead of kLGSideMenuControllerWillDismissLeftViewNotification for show status bar.

**Comment by brightsider** [comment]
@Friend-LGA and will be good solution - add BOOL for animation in progress and don't use layoutInvalidate in viewWillLayoutSubviews before animation don't finished.
Bug appears because calls status bar showing before [self rootViewLayoutInvalidateWithPercentage:0.f]; and it call viewWillLayoutSubviews before completion _leftViewShowing = NO.

It would be nice if it could have a fix. Because hide status bar afrer dismiss looks bad :(

**Comment by Friend-LGA** [comment]
```leftViewStatusBarVisibleOptions``` and ```rightViewStatusBarVisibleOptions``` works fine on iOS 9 with both:
- ```View controller-based status bar appearance = YES;```
- ```View controller-based status bar appearance = NO;```

This bug was fixed too. Do you sure it still exists?

**Comment by brightsider** [comment]
@Friend-LGA leftViewStatusBarVisibleOptions and rightViewStatusBarVisibleOptions seems don't work on iOS 9. https://www.dropbox.com/s/j0g58t7acvqh6s3/LGSideMenuController-master.zip?dl=0 - in Demo reproducing not hidding status bar.

**Comment by brightsider** [comment]
@Friend-LGA and call in-call status bar when animation in progress.

**Comment by brightsider** [comment]
@Friend-LGA nice! thanks!

**Comment by ndmeiri** [comment]
@Friend-LGA I still can't seem to get the status bar visible options to work on iOS 9 with `View controller-based status bar appearance` set to `YES`. I do the following in `init!(rootViewController: UIViewController!)`, but the status bar does not animate to hidden when the menu is shown.

```
self.setLeftViewEnabledWithWidth(self.menuWidth,
    presentationStyle: LGSideMenuPresentationStyleSlideBelow,
    alwaysVisibleOptions: LGSideMenuAlwaysVisibleOnNone)
        
self.leftViewStatusBarVisibleOptions = LGSideMenuStatusBarVisibleOnNone
```

**Comment by aparna1591** [comment]
@ndmeiri 
I am facing the same issue, did you happen to find a solution for this?

**Comment by ndmeiri** [comment]
@aparna1591 Sorry, I have not yet found a solution.

**Comment by Friend-LGA** [comment]
Looks like you don't have strong reference to your view.
Try new version, it is working in a little different way, everything should be fine.
