### ISSUE TITLE
set background color & image won't work with storyboard

### ISSUE THREAD

**Issue by armnotstrong** [Friend-LGA/LGSideMenuController#140]
Hi,

   I am trying to follow the Object-C-storyboard-demo, but I can't set the left/right view background color and left/right view background image.

I have checked the inspector of the viewController in the storyboard multi times, but can't find any different why this happen, could anyone give some hint?

Thanks in advance

Here is the screenshot of the storyboard with the attribute

![wx20171130-223749](https://user-images.githubusercontent.com/3839691/33436320-a90f4f1e-d61f-11e7-82b6-9eb7d5d2fade.png)

As shown in the inspector the background color or the image should show, but none of them happen, I also tried to assign it via code:

```
@implementation MainViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    self.leftViewBackgroundImage = [UIImage imageNamed:@"imageLeft.png"];
    self.rightViewBackgroundImage = [UIImage imageNamed:@"imageRight.png"];
    // Do any additional setup after loading the view.
}

```

But got no luck either.

**Comment by Friend-LGA** [comment]
You have to provide your own images, images from Demo are not included with the library.
Colors should be visible if you installed everything correctly. It might be that your left and right views have it's own backgrounds, which is why `leftViewBackgroundColor` and `rightViewBackgroundColor` are not visible through.
Please, take a look again at the new Demo Projects, they have tons of examples. Just follow them.
