### ISSUE TITLE
Menu issue

### ISSUE THREAD

**Issue by chlebta** [Friend-LGA/LGSideMenuController#25]
Hello,  I'm using the last version and when I scroll my menu it disappear (the tableview cell became empty). I'm using static tableview and the menu works fine with MMDrawerController. 

(before big image) (after scrolling the small image)
![untitled](https://cloud.githubusercontent.com/assets/1204608/11719546/8bb9f7ae-9f5b-11e5-9ca8-b79d8698f3ee.png)

This issue may have relation with this one : https://github.com/Friend-LGA/LGSideMenuController/issues/18

**Comment by FreshApps** [comment]
Hi i have to same problem. Did you find a solution for that? I currently work with Swift

**Comment by chlebta** [comment]
@FreshApps nope I'm using MMDrawerController now because I don't have much time to look to library , find the issue then fix it

**Comment by jpaas** [comment]
Same issue here. Using Swift. Scrolling or selecting a cell causes all cells to vanish.

**Comment by jpaas** [comment]
Ha! Sometimes pasting the code helps you think about things. In my case the problem is that although I am adding the tableView of my MenuController as a subview of the leftView of my LGSideMenuController, I was using a local variable to create the MenuController which means nobody was holding on to a reference to it. So by the time I went to scroll or select, the controller had been GC'd. Changing the variable to a property on my AppDelegate fixed it.

One could argue that is a design flaw. Perhaps the LGSideMenuController should hold a reference to the controller for the left and right views?

**Comment by Friend-LGA** [comment]
Looks like you don't have strong reference to your view or something like that.
Try new version, a lot of bugs was fixed.
