### ISSUE TITLE
Changing Content Glitches Status Bar

### ISSUE THREAD

**Issue by dtfiedler** [Friend-LGA/LGSideMenuController#37]
I have a tableview as my left menu. When I select a row I then switch the content of the LGSideMenuController to my new view controller and dismiss the Side menu. However, when I do that the new content loads without a status bar, then after a second loads the status bar and looks somewhat like a glitch. Any recommendations on this issue?

I currently have View Controller Based Status Bar to YES, and have tried using 

`override func preferredStatusBarUpdateAnimation() -> UIStatusBarAnimation {
        return .Fade 
    }`

in almost every view controller (including the menu view controller, the content view controllers, etc.) but still experiencing this issue.

**Comment by dtfiedler** [comment]
Fixed the issue by changing "View Controller controlled status bar" in info.plist to NO, then setting             UIApplication.sharedApplication().setStatusBarHidden(BOOL, withAnimation: .None) to either true or false.

**Comment by keithyipkw** [comment]
It is caused by the status bar handling in LGSideMenuController. The sequence is

1. Hide the status bar
2. Show the side menu
3. Show the content view
4. Show the status bar

Between 2 and 3, if a view controller is displayed, the status bar is not in the top layout guide because the status bar is hidden. If your view controller depends on the top layout guide, like using opaque navigation bars or placing a toolbar below the navigation bar, you will be affected by this problem.

My navigation bars somehow leave the correct space for the status bar to appear but the content views do not. I simply show the status bar even when the side menu appears.

**Comment by Friend-LGA** [comment]
Try new version, is it ok now?

**Comment by Friend-LGA** [comment]
Feel free to open issue back if you have more questions.
