### ISSUE TITLE
Using a UIViewController with a UITableView instead of UITableViewController

### ISSUE THREAD

**Issue by kyco16** [Friend-LGA/LGSideMenuController#50]
I have got this pod to work with by using `UITableViewController`but for design purposes I'd like to use a `UIViewController` with a navigation bar and view for status bar background. I tried duplicating my originally `UITableViewController` because it worked with my "design idea" and for some reason `viewDidLoad` isn't even being called anymore and `self.tableView = nil` even though it is an IBO outlet

Why is that?

**Comment by rocbird** [comment]
You will need to drag a UITableView from IB ( or by code ) connect to UIViewController named tableView first. 

viewDidLoad not called is because UIViewController's view is not the tableView.  With UITableViewController , you will found self.view  and self.tableView are the same. for UIViewController , You may need something like :

`_leftViewController.view;`

to force viewDidLoad be called. 

When you connect an UITableView , setup the delegate &  datasource , make it as leftViewController , addsubview to leftView ..... you will found that it is still blank.

The problem is constraint, you have to add constraint  after : 

`[self.leftView addSubview:_leftViewController.tableView];`

, by manually or with something like PureLayout 

`[_leftViewController.tableView autoPinEdgesToSuperviewEdges];`

Finally , you can have your UIViewController shown on leftMenu . 

That is all what i have done , but i have no idea if  there is any problem hidden .

**Comment by Friend-LGA** [comment]
Is not related to this framework
