### ISSUE TITLE
rootViewController removed when showing left or right menu

### ISSUE THREAD

**Issue by Chris59160** [Friend-LGA/LGSideMenuController#67]
Hello,

I think I have found a bug out.

When you wanna show the left or right menu, the function that prepares it for left is as below
- (void)showLeftViewPrepare
  {
  [self.view endEditing:YES];
  
  _leftViewShowing = YES;
  
  // -----
  
  if (kLGSideMenuSystemVersion >= 7.0)
  {
      _savedStatusBarHidden = kLGSideMenuStatusBarHidden;
      _savedStatusBarStyle = kLGSideMenuStatusBarStyle;
  
  ```
  [_rootVC removeFromParentViewController];
  ```

I don't understand why it removes the root from its parent controller. It was causing obviously a bug for me. So I commented out the line, and the line to put it back...the menu works perfectly fine.

So were those lines forgotten or is there a non-obvious reasons for those 2 lines ?

**Comment by Friend-LGA** [comment]
Because if you will not do this, and you will want to hide status bar, navigation bar will change its height.

* Side views hidden, StatusBar showed, NavigationBar height = 64
* Perform action: show side view and hide StatusBar
  * if _rootVC is still childViewController then it will change NavigationBar height to 44
  * if _rootVC is removed from parentViewController then it will not change NavigationBar height
